# Generated by Django 3.1.4 on 2020-12-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20201203_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('DN', 'Donor'), ('RC', 'Recipient'), ('CH', 'Champion')], default='CH', max_length=2),
        ),
    ]
